#!/bin/sh
# chkconfig: 2345 95 20
# Provides: start-pentaho stop-pentaho
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Description: Pentaho BA Server
username=pentaho
start_pentaho_script="/opt/pentaho/biserver-ce/start-pentaho.sh"
stop_pentaho_script="/opt/pentaho/biserver-ce/stop-pentaho.sh"
prog="pentaho"


check_status()
{
  if [ $? = 0 ]
  then
    echo "OK"
  else
    echo "FAILED"
  fi
}

case "$1" in
"start")
echo -n $"Starting $prog: ..."
su - $username -c "$start_pentaho_script"
check_status
;;
"stop")
echo -n $"Stopping $prog: ..."
su - $username -c "$stop_pentaho_script"
check_status
;;
*)
echo "Usage: $0 { start | stop }"
;;
esac
exit 0
